language: docker

services:
  - docker

before_script:
  - docker login -u "$DOCKER_USERNAME" --password-stdin < "$DOCKER_PASSWORD"

script:
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-api-feed truongthuan/udagram-api-feed:v1
  - docker tag udagram-api-user truongthuan/udagram-api-user:v1
  - docker tag udagram-frontend truongthuan/udagram-frontend:v1
  - docker tag udagram-reverseproxy truongthuan/udagram-reverseproxy:v1
  - docker push truongthuan/udagram-api-feed:v1
  - docker push truongthuan/udagram-api-user:v1
  - docker push truongthuan/udagram-frontend:v1
  - docker push truongthuan/udagram-reverseproxy:v1